#project:
  #execute-dir: project
#  render:
 #   - "*.qmd"
  #  - "!index.qmd"


toc: true
number-sections: true
bibliography: references.bib
csl: apa.csl
language: 
  title-block-published: "Last updated:"

format:
  html:
    html-math-method: katex
    page-layout: article
    code-fold: show
  pdf:
    documentclass: report
    margin-left: 30mm
    margin-right: 30mm

theme:
  light: flatly
  dark: darkly

execute:
  fig.retina: 2 
  echo: true
  message: false
  warning: false
  freeze: auto

editor: source

knitr:
  opts_chunk: 
    fig.path: "figs/"
